namespace GizmoGrid._01.Dto
{
    public class FlowDiagramDtoReturn
    {

        public Guid Id { get; set; }         // Auto-generated by backend
        public string Label { get; set; }
        public Guid ProjectId { get; set; }
        public List<NodeDtoReturn> Nodes { get; set; } = new();
    }
}
